# Generated by Django 4.1.2 on 2023-10-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_fullname', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('ministry', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('prospects', 'Prospects'), ('lead', 'Lead'), ('conversion', 'Conversion')], max_length=20)),
                ('pf_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('pf_number_conversion', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('comment_conversion', models.TextField(blank=True, null=True)),
                ('type_loan_qualify', models.CharField(blank=True, choices=[('refinance', 'Refinance'), ('topup', 'Top-Up'), ('buyoff', 'Buy-Off')], max_length=20, null=True)),
            ],
        ),
    ]
