# Generated by Django 4.1.2 on 2023-10-06 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='ID number must be 7 to 8 digits long.', regex='^[0-9]{7,8}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 to 12 digits long.', regex='^[0-9]{10,12}$')]),
        ),
    ]
