# Generated by Django 4.2.6 on 2023-10-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_sale_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
